### ISSUE TITLE
bitbake core-image-minimal-xfce4 fails

### ISSUE THREAD

**Issue by tegoo** [Freescale/fsl-community-bsp-base#10]
Building core-image-minimal-xfce4 fails with machine set to wandboard / imx6dlsabreauto.conf (morty branch).
```
| ../../libxfce4ui-4.12.1/libxfce4ui/xfce-sm-client.c:60:22: fatal error: gdk/gdkx.h: No such file or directory
|  #include <gdk/gdkx.h>
```
Something removes gdk/* headers from 
/tmp/sysroots/MACHINE/usr/include/gtk-3.0/

It is present there in the begining of build process, but then disappears and compilation of libxfce4ui fails with error above.

Thanks in advance for your support.

**Comment by otavio** [comment]
Please discuss that on openembedded-devel mailing list as it does not seem to be BSP specific.

**Comment by tegoo** [comment]
It compiles successfully when setting MACHINE to qemuarm leaving the same distro & image.

**Comment by otavio** [comment]
Good, in this case we need to handle this in the meta-freescale mailing list.

**Comment by tegoo** [comment]
Should I drop a mail describing issue to the mailing list?

**Comment by otavio** [comment]
Sure; please do.

Also see if you figure out why the dependency is not being added. Check for bbappend files which might be causing it to fail.

**Comment by tegoo** [comment]
I did:
https://lists.yoctoproject.org/pipermail/meta-freescale/2017-September/021087.html
