### ISSUE TITLE
MACHINE and DISTRO environment variables are unset even if they were set explicitly

### ISSUE THREAD

**Issue by maximdeclercq** [Freescale/fsl-community-bsp-base#15]
It's possible that someone that's automating the build needs these variables after the build.
In my particular case, I needed the MACHINE variable to find the directory with images.
It was very confusing to me why and where these variables disappeared after the build.

On another note, if someone would like to run `export MACHINE=imx7d-pico` to configure their environment, this would be unset on subsequent calls of `source setup-environment`, resulting in very confusing behavior.

A function with local variables would seem like a nice solution to me. I'll see if I find the time to make a pull request.

**Comment by otavio** [comment]
Hello @maximdeclercq; please take a look at https://github.com/OSSystemsEmbeddedLinux/ossystems-embedded-linux-platform where we use our next gen scripts and we provide means to do that kind of thing using Python.
