### ISSUE TITLE
Master build is broken at parsing stage

### ISSUE THREAD

**Issue by zandrey** [Freescale/fsl-community-bsp-base#17]
I'm seeing a lot of warnings and several errors when trying to use the build setup from this manifest.

Steps to reproduce the issue:
1. `repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b master`
2. `repo sync`
3. setup for _i.MX8M Mini EVK_ board: `EULA=1 MACHINE=imx8mm-lpddr4-evk DISTRO=poky source setup-environment build`
4. `bitbake core-image-base`

_NOTE_: On consecutive invocation of the `bitbake core-image-base` command - the build proceeds without warnings or errors, it happens only when above sequence is invoked.

Following errors are observed:
```
ERROR: Nothing RPROVIDES 'libssp-nonshared-staticdev' (but /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-core/musl/musl_git.bb RDEPENDS on or otherwise requires it)
libssp-nonshared RPROVIDES libssp-nonshared-staticdev but was skipped: incompatible with host aarch64-poky-linux (not in COMPATIBLE_HOST)
NOTE: Runtime target 'libssp-nonshared-staticdev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libssp-nonshared-staticdev']
ERROR: Nothing RPROVIDES 'bsd-headers-dev' (but /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-core/musl/musl_git.bb RDEPENDS on or otherwise requires it)
bsd-headers RPROVIDES bsd-headers-dev but was skipped: incompatible with host aarch64-poky-linux (not in COMPATIBLE_HOST)
NOTE: Runtime target 'bsd-headers-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['bsd-headers-dev']
ERROR: Nothing RPROVIDES 'musl-dev' (but /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-core/musl/musl_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'musl-dev'
NOTE: Runtime target 'musl-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['musl-dev']
ERROR: Nothing RPROVIDES 'musl' (but /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-core/musl/musl_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'musl'
NOTE: Runtime target 'musl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['musl']
ERROR: Nothing PROVIDES 'bsd-headers' (but /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-core/musl/musl_git.bb DEPENDS on or otherwise requires it)
bsd-headers was skipped: incompatible with host aarch64-poky-linux (not in COMPATIBLE_HOST)
ERROR: Nothing PROVIDES 'libssp-nonshared' (but /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-core/musl/musl_git.bb DEPENDS on or otherwise requires it)
libssp-nonshared was skipped: incompatible with host aarch64-poky-linux (not in COMPATIBLE_HOST)
WARNING: preferred version 1.20.imx of wayland-protocols not available (for item wayland-protocols)
WARNING: versions of wayland-protocols available: 1.20
WARNING: preferred version 1.20.imx of wayland-protocols not available (for item wayland-protocols)
WARNING: versions of wayland-protocols available: 1.20
```

There are also a lot of warnings reported about the replacement of preferred providers, like following:
```
WARNING: /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-graphics/ttf-fonts/liberation-fonts_2.00.1.bb: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}compilerlibs (gcc-runtime) replaces original key PREFERRED_PROVIDER_virtual/x86_64-pokysdk-linux-compilerlibs (nativesdk-gcc-runtime).
WARNING: /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-graphics/ttf-fonts/liberation-fonts_2.00.1.bb: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}g++ (gcc-cross-${TARGET_ARCH}) replaces original key PREFERRED_PROVIDER_virtual/x86_64-pokysdk-linux-g++ (gcc-crosssdk-${SDK_SYS}).
WARNING: /storage/projects/fsl-bsp-from-manifest/sources/poky/meta/recipes-graphics/ttf-fonts/liberation-fonts_2.00.1.bb: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}gcc (gcc-cross-${TARGET_ARCH}) replaces original key PREFERRED_PROVIDER_virtual/x86_64-pokysdk-linux-gcc (gcc-crosssdk-${SDK_SYS}).
WARNING: /storage/projects/fsl-bsp-from-manifest/sources/meta-openembedded/meta-python/recipes-devtools/python/python3-html5lib_1.1.bb: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}compilerlibs (gcc-runtime) replaces original key PREFERRED_PROVIDER_virtual/x86_64-pokysdk-linux-compilerlibs (nativesdk-gcc-runtime).
WARNING: /storage/projects/fsl-bsp-from-manifest/sources/meta-openembedded/meta-python/recipes-devtools/python/python3-html5lib_1.1.bb: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}g++ (gcc-cross-${TARGET_ARCH}) replaces original key PREFERRED_PROVIDER_virtual/x86_64-pokysdk-linux-g++ (gcc-crosssdk-${SDK_SYS}).
WARNING: /storage/projects/fsl-bsp-from-manifest/sources/meta-openembedded/meta-python/recipes-devtools/python/python3-html5lib_1.1.bb: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}gcc (gcc-cross-${TARGET_ARCH}) replaces original key PREFERRED_PROVIDER_virtual/x86_64-pokysdk-linux-gcc (gcc-crosssdk-${SDK_SYS}).
```

Can this be taken care of? This has been reported several times already: at least once on [meta-freescale ML indirectly](https://lists.yoctoproject.org/g/meta-freescale/message/24616) and once in [PR in meta-freescale layer](https://github.com/Freescale/meta-freescale/pull/668#issuecomment-787476631).

-- andrey

**Comment by pberginkonsult** [comment]
I have tried to narrow this down a bit and my wild guess is that this has something with setup-environment script to do. My build host is Ubuntu 20.10 (that I know is not a validated build host).

Here is an experiment where I create one build dir with setup-environment this ends up in the error described above and works the second time. Then I create a new build dir with oe-init-build-env and then copy local.conf and bblayers.conf from the first build dir.

    $ EULA=1 MACHINE=imx6qdlsabresd DISTRO=poky source setup-environment build
    $ bitbake core-image-base
    <ERROR>
    $ cd ..
    $ . ./sources/poky/oe-init-build-env build2
    $ cp ../build/conf/bblayers.conf conf/
    $ cp ../build/conf/local.conf conf/
    $ bitbake core-image-base
    <OK> 

I ahev also tested with and without prepopulated sstate and with different machines without any changes. The only thing I've seen working is the different setup scripts.

/Peter

**Comment by thochstein** [comment]
We saw this as well and narrowed it down to this: https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=8b792d4f75b451f9e08fdb13464a0b66c11bc075. We tried `master-next` just an hour ago and it appears fixed on that branch.

**Comment by hutchman** [comment]
> I have tried to narrow this down a bit and my wild guess is that this has something with setup-environment script to do. My build host is Ubuntu 20.10 (that I know is not a validated build host).
> 
> Here is an experiment where I create one build dir with setup-environment this ends up in the error described above and works the second time. Then I create a new build dir with oe-init-build-env and then copy local.conf and bblayers.conf from the first build dir.
> 
> ```
> $ EULA=1 MACHINE=imx6qdlsabresd DISTRO=poky source setup-environment build
> $ bitbake core-image-base
> <ERROR>
> $ cd ..
> $ . ./sources/poky/oe-init-build-env build2
> $ cp ../build/conf/bblayers.conf conf/
> $ cp ../build/conf/local.conf conf/
> $ bitbake core-image-base
> <OK> 
> ```
> 
> I ahev also tested with and without prepopulated sstate and with different machines without any changes. The only thing I've seen working is the different setup scripts.
> 
> /Peter

For full disclosure I'm also running Ubuntu 20.04.  I originally reported seeing this in https://lists.yoctoproject.org/g/meta-freescale/message/24623

**Comment by pberginkonsult** [comment]
I can confirm it is fixed in master-next by this commit https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=83c161ca98a53fb5bc6e0726ae139607f89a3823

**Comment by otavio** [comment]
We can close this once it hits master :)
