### ISSUE TITLE
setup-environment fails unless system shell is /bin/bash

### ISSUE THREAD

**Issue by nickleverton** [Freescale/fsl-community-bsp-base#2]
The shebang line on ./setup-environment invokes the script with /bin/sh

However the script only works if sh == /bin/bash/ .  This causes at least two problems on modern distros  where dash provides /bin/sh.

First, directory 'build' gets created underneath sources/poky.  Reason is that supplying parameters to "sourced" scripts  is a bash extension.

Also, the script also uses "echo -e" which, under some shells, results in a literal "-e" being echoed.  This interferes with checking and listing the supported machine types.

Simple fix is to replace #!/bin/sh with #!/bin/bash

A more complex fix would be possible such as is used by Poky's own oe-init scripts if preferred, but I have gone for minimal changes at the moment.  This doesn't change the Freescale BSP shell requirement, just makes it explicit.

**Comment by nickleverton** [comment]
Actually this is incomplete, sorry.  Because you're sourcing this from a possible non-bash shell anyway it needs to have a proper fix.

**Comment by angolini** [comment]
I think #3 fixes this
