### ISSUE TITLE
Pyro release

### ISSUE THREAD

**Issue by tegoo** [Freescale/fsl-community-bsp-base#8]
I have a project on top of Wandboard Solo Rev. D1 board. Unfortunately, I have noticed that support of this bord is not presend in stable branch ("morty"), so I have two options: base on top of "morty" and do necessary changes to u-boot, kernel or I can just wait for "pyro" release. 

When do you plan to release "pyro"? 

Thanks in advance for your answer.

**Comment by otavio** [comment]
The revision D has not been yet send for merge on meta-freescale. Until someone does it is not going to be supported...
