### ISSUE TITLE
setup-environment clobbers bblayers.conf when using TEMPLATECONF

### ISSUE THREAD

**Issue by tescott-jdes** [Freescale/fsl-community-bsp-base#9]
If you attempt to use TEMPLATECONF to define an alternate bblayers.conf, the setup-environment script will overwrite it which is unexpected behavior.  This is due to the script line that explicitly copies from the local templates to the build path conf/ dir, losing the template brought in by the TEMPLATECONF usage.

Note that the treatment of local.conf works because the script in this case modifies what is copied rather than overwriting what is used, so using TEMPLATECONF in that respect works.

https://github.com/Freescale/fsl-community-bsp-base/blob/70535e13dd2aabbad53243518f4cc5064d284592/setup-environment#L166

Recommend removing the explicit copy and that templates get copied via a default TEMPLATECONF value that can be properly overridden at the command-line.

**Comment by otavio** [comment]
Please prepare a pull request for it, so we can review it.
